export { default as HomePage } from "./home/home";
export { default as NotfoundPage } from "./notFound/NotFound";
export { default as ProfilePage } from "./profile/profile";
// export { default as TasksPage } from "./tasks/tasks";
export { default as ItemsMasterPage } from "./masters/item-master/items.master";
export { default as ItemsGroupMasterPage } from "./masters/item-group-master/items-group-master";
export { default as AddItemsGroupMasterPage } from "./masters/item-group-master/add";
export { default as GateInPage } from "./purchases/gate-in/gate-in";
export { default as GateInMainPage } from "./purchases/gate-in/gate-in-main";
export { default as GatePrintQrPage } from "./purchases/gate-in/print-qr/print-qr";
export { default as GrpoPage } from "./purchases/grpo/grpo-main";
export { default as GrpoScanItemsPage } from "./purchases/grpo/grpo-items";
export { default as UomMasterPage } from "./masters/uom-master/uom-master";
export { default as WarehouseMasterPage } from "./masters/warehouse-master/warehouse-master";
export { default as LocationMasterPage } from "./masters/location-master/location-master";
export { default as DepartmentMasterPage } from "./masters/department-master/department-master";
export { default as ItemsubgroupmasterPage } from "./masters/item-sub-group-master/item-sub-group-master";
export { default as MachinemasterPage } from "./masters/machine-master/machine-master";
export { default as EmployeemasterPage } from "./masters/employee-master/employee-master";
export { default as IncomingQCPage } from "./qualityControl/incomigQualityControl/incomingQC-main";
export { default as InprocessQCPage } from "./qualityControl/inprocessQualityControl/inprocessQC-main";
export { default as InprocessQcScanItemsPage } from "./qualityControl/inprocessQualityControl/inprocessQcScanItemsPage";
export { default as IncomingQcScanItemsPage } from "./qualityControl/incomigQualityControl/IncomingQcScanItemsPage";
export { default as MasterPage } from "./masters/master/master";
export { default as QualityControlPage } from "./qualityControl/qualityControls/qualityControls";
export { default as ProductionPage } from "./production/productions/productions";
export { default as InventoryPage } from "./inventory/inventories/inventories";
// production module
export { default as VerifyMaterialPage } from "./production/verify-material/verify-material-main";
export { default as VerifyMaterialScanItemsPage } from "./production/verify-material/tabs-content/VerifyScanItems";
export { default as ReceiveMaterialPage } from "./production/receive-material/receive-material.main";
export { default as ReceiveMaterialScanItemsPage } from "./production/receive-material/receive-material-scan-items";
export { default as ReceiveMaterialGenerateQrPage } from "./production/receive-material/generateReceipt-qr/generate-receipt.main";
export { default as IssueMaterialPage } from "./production/issue-material/issue-material-main";
export { default as IssueMaterialScanItemsPage } from "./production/issue-material/issue-material-scan-items";
export { default as InventoryTransferMainPage } from "./inventory/inventory-transfer/inventory-transfer-main";
export { default as PickPackMain } from "./inventory/pick-pack/Pick-pack-main";
export { default as PickPackProcess } from "./inventory/pick-pack/Pick-pack-process";
export { default as PurchasePage } from "./purchases/purchase/purchase";
export { default as SalePage } from "./sales/salesIndex/sale";
export { default as DeliveryPage } from "./sales/delivery/delivery";

export { default as MachineInOutPage } from "./Track Machines/MachineInOut";
export { default as MachineManagementPage } from "./Track Machines/MachineManagement";
export { default as VarifyMaterialScanItemPage } from "./production/verify-material/varify-material-scanItemPage";
